"use strict";
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getOwnPropSymbols = Object.getOwnPropertySymbols;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __propIsEnum = Object.prototype.propertyIsEnumerable;
var __defNormalProp = (obj, key, value) => key in obj ? __defProp(obj, key, { enumerable: true, configurable: true, writable: true, value }) : obj[key] = value;
var __spreadValues = (a, b) => {
  for (var prop in b || (b = {}))
    if (__hasOwnProp.call(b, prop))
      __defNormalProp(a, prop, b[prop]);
  if (__getOwnPropSymbols)
    for (var prop of __getOwnPropSymbols(b)) {
      if (__propIsEnum.call(b, prop))
        __defNormalProp(a, prop, b[prop]);
    }
  return a;
};
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/vite.ts
var vite_exports = {};
__export(vite_exports, {
  default: () => vite_default
});
module.exports = __toCommonJS(vite_exports);

// src/core/index.ts
var import_cors = __toESM(require("cors"), 1);
var import_etag = __toESM(require("etag"), 1);
var import_unplugin = require("unplugin");

// src/core/generator.ts
var import_node_path3 = __toESM(require("path"), 1);
var import_promises3 = __toESM(require("fs/promises"), 1);
var import_node_process3 = __toESM(require("process"), 1);
var import_local_pkg = require("local-pkg");
var import_picocolors = __toESM(require("picocolors"), 1);

// src/core/constants.ts
var LOAD_EVENT = "svg-component:reload";
var MODULE_NAME = "~virtual/svg-component";
var PLUGIN_NAME = "unplugin-svg-component";

// src/core/snippets.ts
var dtsComments = `
/* eslint-disable */
/* prettier-ignore */
// biome-ignore format: off
// biome-ignore lint: off
// @ts-nocheck
// Generated by unplugin-svg-component
`.trim();
var template = `
  <svg 
    xmlns="http://www.w3.org/2000/svg" 
    xmlns:xlink="http://www.w3.org/1999/xlink" 
    style="$component_style"
    $component_class
    v-on="$listeners"
  >
    <use :xlink:href="'#' + name" />
  </svg>
`;
var dts = `${dtsComments}
declare module '${MODULE_NAME}' {
  const $component_name: import("vue").DefineComponent<{
      name: {
          type: import("vue").PropType<"$svg_symbolIds">;
          default: string;
          required: true;
      };
  }, {}, unknown, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {}, string, import("vue").VNodeProps & import("vue").AllowedComponentProps & import("vue").ComponentCustomProps, Readonly<import("vue").ExtractPropTypes<{
      name: {
          type: import("vue").PropType<"$svg_symbolIds">;
          default: string;
          required: true;
      };
  }>>, {
      name: "$svg_symbolIds";
  }>;
  export const svgNames: ["$svg_names"];
  export type SvgName = "$svg_symbolIds";
  export default $component_name;
}
`;
var golbalDts = `${dtsComments}
import 'vue'
declare module 'vue' {
  export interface GlobalComponents {
    $component_name: import("vue").DefineComponent<{
        name: {
            type: import("vue").PropType<"$svg_symbolIds">;
            default: string;
            required: true;
        };
    }, {}, unknown, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {}, string, import("vue").VNodeProps & import("vue").AllowedComponentProps & import("vue").ComponentCustomProps, Readonly<import("vue").ExtractPropTypes<{
        name: {
            type: import("vue").PropType<"$svg_symbolIds">;
            default: string;
            required: true;
        };
    }>>, {
        name: "$svg_symbolIds";
    }>;
  }
}
`;
var reactTemplate = `
import React from 'react';

export default function $component_name({name,style,className}) {
  return React.createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    xmlnsXlink: "http://www.w3.org/1999/xlink",
    style: {...$component_style, ...style},
    className: [className, $component_class || ''].filter(cls=> !!cls).join(" ") || undefined,
  }, React.createElement("use", {
    xlinkHref: "#" + name
  }));
}
`;
var reactDts = `${dtsComments}
declare module '${MODULE_NAME}' {
  const $component_name: (props: {
    name: "$svg_symbolIds"
    className?: string
    style?: React.CSSProperties
  }) => JSX.Element;
  export const svgNames: ["$svg_names"];
  export type SvgName = "$svg_symbolIds";
  export default $component_name;
}
`;

// src/core/utils.ts
var import_node_process = __toESM(require("process"), 1);
function debounce(fn, delay) {
  let timer;
  return function(...args) {
    if (timer)
      clearTimeout(timer);
    timer = setTimeout(() => {
      fn.apply(this, args);
      clearTimeout(timer);
    }, delay);
  };
}
function replace(dts2, symbolIds, componentName) {
  return dts2.replace(
    /\$svg_symbolIds/g,
    Array.from(symbolIds).join('" | "')
  ).replace(
    /\$component_name/g,
    componentName
  ).replace(
    /\$svg_names/g,
    Array.from(symbolIds).join('", "')
  );
}
function resolveOptions(options) {
  const defaultOptions = {
    hmr: true,
    componentName: "SvgIcon",
    dtsDir: import_node_process.default.cwd(),
    projectType: "auto",
    vueVersion: "auto",
    svgSpriteDomId: "__svg_sprite__dom__",
    componentStyle: "width: 1em; height: 1em; fill:currentColor;",
    symbolIdFormatter(svgName, prefix) {
      const nameArr = svgName.split("\\");
      if (prefix)
        nameArr.unshift(prefix);
      return nameArr.join("-").replace(/\.svg$/, "");
    },
    treeShaking: true,
    scanGlob: [
      "**/*.html",
      "**/*.pug",
      "**/*.vue",
      "**/*.js",
      "**/*.ts",
      "**/*.tsx",
      "**/*.jsx"
    ],
    scanStrategy: "text",
    domInsertionStrategy: "replaceHtml"
  };
  return __spreadValues(__spreadValues({}, defaultOptions), options);
}
function transformStyleStrToObject(styleStr) {
  return styleStr.replace(/;$/, "").split(";").reduce((ruleMap, ruleString) => {
    const rulePair = ruleString.split(":");
    if (!rulePair[0] || !rulePair[1])
      return ruleMap;
    ruleMap[rulePair[0].trim()] = rulePair[1].trim();
    return ruleMap;
  }, {});
}
function tranfromToKebabCase(str) {
  const arr = str.trim().split("");
  const result = arr.map((item, index) => {
    if (index === 0)
      return `${item.toLowerCase()}`;
    else if (item.toUpperCase() === item)
      return `-${item.toLowerCase()}`;
    else
      return item;
  }).join("");
  return result;
}

// src/core/sprite.ts
var import_node_path2 = __toESM(require("path"), 1);
var import_promises2 = __toESM(require("fs/promises"), 1);
var import_fast_glob2 = __toESM(require("fast-glob"), 1);
var import_svgo = require("svgo");
var import_svg_sprite = __toESM(require("svg-sprite"), 1);

// src/core/scan.ts
var import_promises = __toESM(require("fs/promises"), 1);
var import_node_process2 = __toESM(require("process"), 1);
var import_node_path = __toESM(require("path"), 1);
var import_fast_glob = __toESM(require("fast-glob"), 1);
async function scanUsedSvgNames(options) {
  const { componentName, scanGlob, iconDir, scanStrategy, symbolIdFormatter, prefix } = options;
  const filenames = await (0, import_fast_glob.default)(scanGlob, {
    onlyFiles: true,
    ignore: [
      "**/node_modules",
      "**/dist",
      "**/*.d.ts",
      "vite.config.ts",
      "vite.config.js"
    ]
  });
  const code = await Promise.all(filenames.map(async (f) => {
    const code2 = await import_promises.default.readFile(import_node_path.default.resolve(import_node_process2.default.cwd(), f), "utf-8");
    return code2;
  }));
  function internalScanStrategy() {
    let svgNameMatches = [];
    if (scanStrategy === "component") {
      const svgCompnentRE = new RegExp(
        `\\<\\s*(${tranfromToKebabCase(componentName)}|${componentName})[^\\<]+name=[\\"\\'](\\S+)[\\"\\'][^\\<]*\\/\\>`,
        "g"
      );
      svgNameMatches = code.map((c) => {
        return Array.from(c.matchAll(svgCompnentRE)).map((match) => match[2]);
      });
    } else {
      let allSvgNames = [];
      const iconDirs = Array.isArray(iconDir) ? iconDir : [iconDir];
      for (const iconDir2 of iconDirs) {
        allSvgNames = allSvgNames.concat(import_fast_glob.default.sync(["**/*.svg"], { cwd: iconDir2 }).map((n) => symbolIdFormatter(n, prefix)).sort((a, b) => b.length - a.length));
      }
      const svgNameRE = new RegExp(`(${allSvgNames.join("|")})`, "gm");
      svgNameMatches = code.map((c) => {
        return [...c.match(svgNameRE) || []];
      });
    }
    return svgNameMatches.flat();
  }
  if (typeof scanStrategy === "function")
    return scanStrategy(code, options);
  else
    return internalScanStrategy();
}

// src/core/sprite.ts
async function createSvgSprite(options, isBuild2) {
  const usedSvgNames = isBuild2 && options.treeShaking ? await scanUsedSvgNames(options) : void 0;
  const svgSpriteInfo = await compileSvgFiles(options, usedSvgNames);
  return svgSpriteInfo;
}
async function compileSvgFiles(options, usedSvgNames) {
  const { iconDir } = options;
  const svgCompiler = initSvgCompier(options);
  const iconDirs = Array.isArray(iconDir) ? iconDir : [iconDir];
  const symbolIds = /* @__PURE__ */ new Set();
  for (const dir of iconDirs) {
    const svgNames = import_fast_glob2.default.sync(["**/*.svg"], { cwd: dir });
    for (const svgName of svgNames) {
      await addSymbol(
        svgCompiler,
        svgName.replace("/", import_node_path2.default.sep),
        options,
        dir,
        symbolIds,
        usedSvgNames
      );
    }
  }
  const { result: compileResult } = await svgCompiler.compileAsync();
  const sprite = compileResult.symbol.sprite.contents.toString();
  return {
    symbolIds,
    sprite
  };
  function initSvgCompier(options2) {
    const { svgSpriteDomId, prefix, symbolIdFormatter } = options2;
    return new import_svg_sprite.default({
      mode: {
        symbol: true
      },
      svg: {
        xmlDeclaration: false,
        transform: [
          (svg) => {
            const svgStyle = `style="position: absolute; width: 0px; height: 0px;"`;
            return svg.replace(/^<svg/, `<svg id="${svgSpriteDomId}" ${svgStyle}`);
          }
        ]
      },
      shape: {
        id: {
          generator(name) {
            return symbolIdFormatter(name.replace(import_node_path2.default.sep, "/"), prefix || "");
          }
        }
      }
    });
  }
}
async function addSymbol(svgCompiler, svgName, options, iconDir, symbolIds, usedSvgNames) {
  const { preserveColor, symbolIdFormatter, optimizeOptions, prefix = "" } = options;
  const svgPath = import_node_path2.default.resolve(iconDir, svgName);
  const symbolId = symbolIdFormatter(svgName.replace(import_node_path2.default.sep, "/"), prefix);
  const svgContent = await import_promises2.default.readFile(svgPath, { encoding: "utf-8" });
  if (Array.isArray(usedSvgNames) && !usedSvgNames.includes(symbolId))
    return;
  const isPreserveColor = typeof preserveColor === "string" ? svgPath.startsWith(preserveColor) : typeof preserveColor === "object" && preserveColor.test(svgPath);
  const OptimizedSvgContent = await optimizeSvg(svgContent, isPreserveColor, optimizeOptions);
  symbolIds.add(symbolId);
  svgCompiler.add(svgPath, svgName, OptimizedSvgContent);
}
async function optimizeSvg(source, preserveColor, optimizeOptions) {
  const { data: optimizedSvgContent } = await (0, import_svgo.optimize)(source, optimizeOptions);
  if (!optimizedSvgContent) {
    const emptySvgContent = '<svg width="32" height="32" viewBox="0 0 32 32" xmlns="http://www.w3.org/2000/svg"></svg>';
    return emptySvgContent;
  }
  return preserveColor ? optimizedSvgContent : optimizedSvgContent.replace(/stroke="[a-zA-Z#0-9]*"/g, 'stroke="currentColor"').replace(/fill="[a-zA-Z#0-9]*"/g, (p) => {
    if (p.includes("none"))
      return p;
    else
      return 'fill="currentColor"';
  });
}

// src/core/generator.ts
async function genSpriteAndDts(options, isBuild2) {
  const spriteInfo = await createSvgSprite(options, isBuild2);
  if (!isBuild2 && (options == null ? void 0 : options.dts))
    genDts(spriteInfo.symbolIds, options);
  return spriteInfo;
}
async function genCode(options, isDev = false) {
  const spriteInfo = await genSpriteAndDts(options, !isDev);
  const { svgSpriteDomId } = options;
  const { symbolIds, sprite } = spriteInfo;
  const isDynamic = options.domInsertionStrategy === "dynamic";
  const insertSvgCode = isDynamic ? genInsertSvgCode(sprite) : "";
  const componentCode = await genComponentCode(options);
  const hmrCode = `
if (import.meta.hot) {
  import.meta.hot.on("${LOAD_EVENT}", ({ sprite }) => {
    var svgDom = document.querySelector('#${svgSpriteDomId}');
    svgDom.remove();
    var tempDom = document.createElement('div');
    tempDom.innerHTML = sprite; 
    document.body.append(tempDom.firstElementChild);
  })
}
`;
  const symbolIdsCode = `
export const svgNames = ["${[...symbolIds].join('","')}"]
`;
  const code = `
    ${componentCode}
    ${symbolIdsCode}
    ${insertSvgCode}
    ${isDev ? hmrCode : ""}
   `;
  return code;
}
function genInsertSvgCode(sprite) {
  return `
if (typeof window !== 'undefined') {
  function mountSvg() {
    const tempDiv = document.createElement('div');
    tempDiv.innerHTML = '${sprite.trim()}';
    window.document.body.append(tempDiv.firstElementChild);
  }

  if(document.readyState === 'loading') {
    window.document.addEventListener('DOMContentLoaded', mountSvg);
  } else {
    mountSvg();
  }
}
`;
}
function genDts(symbolIds, options) {
  const isVue = isVueProject(options);
  const dtsPath = import_node_path3.default.resolve(options.dtsDir, "./svg-component.d.ts");
  const globalDtsPath = import_node_path3.default.resolve(options.dtsDir, "./svg-component-global.d.ts");
  if (isVue) {
    import_promises3.default.writeFile(
      dtsPath,
      replace(dts, symbolIds, options.componentName)
    );
    import_promises3.default.writeFile(
      globalDtsPath,
      replace(golbalDts, symbolIds, options.componentName)
    );
  } else {
    import_promises3.default.writeFile(
      dtsPath,
      replace(reactDts, symbolIds, options.componentName)
    );
  }
}
function addClass(template2, projectType, cls) {
  return projectType === "vue" ? cls ? template2.replace(/\$component_class/, `class="${cls}"`) : template2.replace(/\$component_class/, "") : template2.replace(/\$component_class/, `"${cls || ""}"`);
}
async function genComponentCode(options) {
  const isVue = isVueProject(options);
  const { componentStyle, componentName, vueVersion, componentClass } = options;
  if (!isVue) {
    return addClass(
      reactTemplate.replace(/\$component_name/, componentName).replace(/\$component_style/, JSON.stringify(transformStyleStrToObject(componentStyle))),
      "react",
      componentClass
    );
  }
  const vueMajorVersion = await getVueVersion(vueVersion);
  if (!vueMajorVersion)
    return "export default {}";
  const tempTemplate = vueMajorVersion === "vue3" ? template.replace('v-on="$listeners"', "") : template;
  const replacedTemplate = addClass(
    tempTemplate.replace(/\$component_style/, componentStyle),
    "vue",
    componentClass
  );
  const templateCode = await compileVueTemplate(replacedTemplate, vueMajorVersion);
  return `${templateCode}

export default {
  name: "${componentName}",
  props: {
    name: {
      type: String,
      required: true
    }
  },
  render
}`;
}
async function compileVueTemplate(template2, vueMajorVersion) {
  const searchPath = import_node_path3.default.resolve(import_node_process3.default.cwd(), "./virtual");
  const version = (await (0, import_local_pkg.getPackageInfo)("vue", { paths: [searchPath] })).version;
  const isOldVue = version < "2.7.0";
  const compilerInVue = version >= "3.2.13" || vueMajorVersion === "vue2" && version >= "2.7.0";
  if (isOldVue)
    throw new Error(import_picocolors.default.red(`[unpluign-svg-component]: unpluign-svg-component requires vue (>=2.7.0) to be present in the dependency tree.`));
  const pkg = compilerInVue ? await (0, import_local_pkg.importModule)("vue/compiler-sfc") : await (0, import_local_pkg.importModule)("@vue/compiler-sfc").catch(() => {
    throw new Error(
      import_picocolors.default.red(`[unpluign-svg-component]: Failed to resolve vue/compiler-sfc. 
        you should install @vue/compiler-sfc@${version} manually or upgrade your vue version to >=3.2.13.`)
    );
  });
  const { compileTemplate } = pkg;
  const { code } = compileTemplate({
    source: template2,
    id: "__svg-component__",
    filename: "virtual:svg-component.vue"
  });
  return code.replace(/export/g, "");
}
async function getVueVersion(vueVerison) {
  var _a;
  if (vueVerison === "auto") {
    try {
      const result = await (0, import_local_pkg.getPackageInfo)("vue");
      if (!result)
        return null;
      return ((_a = result.version) == null ? void 0 : _a.startsWith("2.")) ? "vue2" : "vue3";
    } catch (e) {
      return null;
    }
  } else {
    return `vue${vueVerison}`;
  }
}
function isVueProject(options) {
  if (options.projectType === "auto") {
    try {
      if ((0, import_local_pkg.isPackageExists)("vue"))
        return true;
      else if ((0, import_local_pkg.isPackageExists)("react"))
        return false;
      else
        throw new Error("[unpluign-svg-component] can't detect your project type, please set options.projectType.");
    } catch (e) {
      throw new Error("[unpluign-svg-component] can't detect your project type, please set options.projectType.");
    }
  } else {
    return options.projectType === "vue";
  }
}

// src/core/watcher.ts
var import_picocolors2 = __toESM(require("picocolors"), 1);
function watchIconDir(options, server) {
  const delay = 500;
  const { watcher } = server;
  const { iconDir } = options;
  const iconDirs = Array.isArray(iconDir) ? iconDir : [iconDir];
  const handleIconFilesChangeDebounce = debounce(handleIconFilesChange, delay);
  watcher.on("add", handleIconFilesChangeDebounce).on("unlink", handleIconFilesChangeDebounce).on("change", handleIconFilesChangeDebounce);
  function isValidSvgFile(path4) {
    const isSvgDir = iconDirs.some((dir) => path4.startsWith(dir));
    return isSvgDir && path4.endsWith(".svg");
  }
  async function handleIconFilesChange(path4) {
    if (!isValidSvgFile(path4))
      return;
    const { sprite } = await genSpriteAndDts(options, false);
    notifyClientUpdate(sprite, server);
  }
}
function notifyClientUpdate(sprite, { ws, config }) {
  config.logger.info(
    import_picocolors2.default.green(`unplugin-svg-component reload`),
    { clear: false, timestamp: true }
  );
  ws.send(LOAD_EVENT, { sprite });
}

// src/core/index.ts
var isBuild = false;
var isWebpack = false;
var transformPluginContext;
var viteDevServer;
var unplugin = (0, import_unplugin.createUnplugin)((options) => ({
  name: PLUGIN_NAME,
  async buildStart() {
    options = resolveOptions(options);
    if (!isBuild && viteDevServer && options.hmr)
      watchIconDir(options, viteDevServer);
  },
  resolveId(id) {
    if (id === MODULE_NAME)
      return id;
  },
  loadInclude(id) {
    return id === MODULE_NAME;
  },
  async load() {
    return isBuild || isWebpack ? await genCode(options) : "";
  },
  webpack(compiler) {
    isWebpack = true;
    isBuild = compiler.options.mode === "production";
    if (options.domInsertionStrategy === "dynamic")
      return;
    compiler.hooks.emit.tapAsync(PLUGIN_NAME, async (compilation, callback) => {
      const assets = compilation.assets;
      const originHtml = assets["index.html"]._value;
      const { sprite } = await genSpriteAndDts(options, isBuild);
      const transformedHtml = originHtml.replace(/<\/body>/, `${sprite}</body>`);
      assets["index.html"] = {
        source() {
          return transformedHtml;
        },
        size() {
          return transformedHtml.length;
        }
      };
      callback();
    });
  },
  vite: {
    async configResolved(config) {
      isBuild = config.command === "build";
    },
    transform() {
      if (this._activeId === MODULE_NAME)
        transformPluginContext = this;
    },
    configureServer(server) {
      viteDevServer = server;
      server.middlewares.use((0, import_cors.default)({ origin: "*" }));
      server.middlewares.use(async (req, res, next) => {
        var _a;
        const { pathname } = req.url ? new URL(req.url, "https://example.com") : { pathname: "" };
        if (pathname.endsWith(`/@id/${MODULE_NAME}`)) {
          const code = await genCode(options, true);
          const importAnalysisTransform = (_a = server.config.plugins.find(
            (plugin) => plugin.name === "vite:import-analysis"
          )) == null ? void 0 : _a.transform;
          transformPluginContext.ssr = false;
          const { code: transformedCode } = await importAnalysisTransform.apply(
            transformPluginContext,
            [code, MODULE_NAME, { ssr: false }]
          );
          const etag = (0, import_etag.default)(transformedCode, { weak: true });
          const noneMatch = req.headers["if-none-match"] || req.headers["If-None-Match"];
          if (noneMatch === etag || noneMatch === `W/${etag}` || `W/${noneMatch}` === etag) {
            res.statusCode = 304;
            res.end();
          } else {
            res.statusCode = 200;
            res.setHeader("ETag", etag);
            res.setHeader("Content-Type", "application/javascript");
            res.setHeader("Cache-Control", "no-cache");
            res.end(transformedCode);
          }
        } else {
          next();
        }
      });
    },
    async transformIndexHtml(html) {
      if (options.domInsertionStrategy === "dynamic" || html.includes(options.svgSpriteDomId)) {
        return html;
      } else {
        const { sprite } = await genSpriteAndDts(options, isBuild);
        return html.replace(/<\/body>/, `${sprite}</body>`);
      }
    }
  }
}));
var core_default = unplugin;

// src/vite.ts
var vite_default = core_default.vite;
exports.default = module.exports;